import fs from 'node:fs/promises';
import path from 'node:path';
import { paths } from './config.mjs';
import { dim } from './log.mjs';

/**
 * Turns the collected history into a page per month, grouped under a category
 * per year:
 *
 *   Changelog
 *   ├── 2026
 *   │   ├── August
 *   │   └── July
 *   └── 2025
 *       └── December
 *
 * These are real Markdown files, so the sidebar, search, prev/next links,
 * prerendering and sitemap all treat them like any other page — no special
 * cases anywhere else in the pipeline.
 *
 * Each file only carries a filter (`<fd-changelog month="2026-08">`), never the
 * commits themselves, so its content is stable: a new commit changes no file,
 * and a new month adds one.
 */
const MARKER = '<!-- AUTO-GENERATED by `npm run docs:build` — edits are overwritten. -->';

const MONTHS = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export async function writeChangelogPages(config, commits) {
  const { monthlyPages, monthlyPagesDir } = config.changelog;
  if (!monthlyPages) return;

  const root = path.join(paths.docs(config), monthlyPagesDir);
  const byYear = groupByYear(commits);

  // Nothing to write and nothing to keep: leave the folder untouched rather
  // than deleting pages a build with no history cannot justify removing.
  if (byYear.size === 0) return;

  const expected = new Set();
  let written = 0;

  for (const [year, months] of byYear) {
    const yearDir = path.join(root, year);
    await fs.mkdir(yearDir, { recursive: true });

    // Newest year first, but after any hand-written overview page in the
    // section: a large base keeps years below ordinary positions, and
    // subtracting the year keeps them descending among themselves.
    // `generated` marks it as ours to remove later; the pipeline reads only
    // label and position, so the extra key is inert.
    const category = { label: year, position: 10_000 - Number(year), generated: true };
    const categoryPath = path.join(yearDir, '_category.json');
    expected.add(categoryPath);
    if (await writeIfChanged(categoryPath, `${JSON.stringify(category, null, 2)}\n`)) written += 1;

    for (const [month, count] of months) {
      const index = Number(month.slice(5, 7));
      const name = MONTHS[index - 1];
      const file = path.join(yearDir, `${name.toLowerCase()}.md`);
      expected.add(file);
      if (await writeIfChanged(file, monthPage(name, year, month, count))) written += 1;
    }
  }

  const pruned = await pruneGenerated(root, expected);
  if (written > 0 || pruned > 0) {
    console.log(
      `  ${dim(`changelog pages: ${written} written, ${pruned} removed ${path.relative(paths.root ?? process.cwd(), root)}`)}`,
    );
  }
}

function monthPage(name, year, month, count) {
  const plural = count === 1 ? 'change' : 'changes';
  return (
    `---\n` +
    `title: '${name} ${year}'\n` +
    `sidebar_label: '${name}'\n` +
    `description: '${count} ${plural} released in ${name} ${year}.'\n` +
    // Newest month first within the year.
    `sidebar_position: ${-Number(month.slice(5, 7))}\n` +
    `---\n\n` +
    `${MARKER}\n\n` +
    `# ${name} ${year}\n\n` +
    `<fd-changelog month="${month}"></fd-changelog>\n`
  );
}

/** Commits per 'YYYY-MM', keyed by year — newest first, empty months skipped. */
function groupByYear(commits) {
  const counts = new Map();
  for (const commit of commits) {
    // Slice the ISO string rather than parsing it: a Date would reinterpret the
    // commit's own offset in the build machine's timezone and could move a
    // commit into a neighbouring month. The component slices it the same way.
    const month = String(commit.date).slice(0, 7);
    if (!/^\d{4}-\d{2}$/.test(month)) continue;
    counts.set(month, (counts.get(month) ?? 0) + 1);
  }

  const byYear = new Map();
  for (const month of [...counts.keys()].sort().reverse()) {
    const year = month.slice(0, 4);
    if (!byYear.has(year)) byYear.set(year, []);
    byYear.get(year).push([month, counts.get(month)]);
  }
  return byYear;
}

/**
 * Removes month pages and year categories this build did not produce — a
 * lowered `limit` or rewritten history would otherwise leave orphans behind.
 * Only files carrying the marker are touched, so a hand-written page that
 * happens to live here survives.
 */
async function pruneGenerated(root, expected) {
  let pruned = 0;
  let years;
  try {
    years = await fs.readdir(root, { withFileTypes: true });
  } catch {
    return 0;
  }

  for (const entry of years) {
    if (!entry.isDirectory() || !/^\d{4}$/.test(entry.name)) continue;
    const yearDir = path.join(root, entry.name);
    const files = await fs.readdir(yearDir);

    for (const file of files) {
      const full = path.join(yearDir, file);
      if (expected.has(full)) continue;

      if (file === '_category.json') {
        // Only ours. A year folder someone curated by hand keeps its own.
        const raw = await fs.readFile(full, 'utf8').catch(() => '');
        if (!JSON.parse(raw || '{}').generated) continue;
        await fs.rm(full, { force: true });
        pruned += 1;
        continue;
      }
      if (!file.endsWith('.md')) continue;

      const contents = await fs.readFile(full, 'utf8').catch(() => '');
      if (!contents.includes(MARKER)) continue;
      await fs.rm(full, { force: true });
      pruned += 1;
    }

    // An empty year folder would render as an empty category.
    const left = await fs.readdir(yearDir);
    if (left.length === 0) await fs.rmdir(yearDir).catch(() => {});
  }

  return pruned;
}

/** Returns true when the file was actually written. */
async function writeIfChanged(file, contents) {
  const existing = await fs.readFile(file, 'utf8').catch(() => null);
  if (existing === contents) return false;
  await fs.writeFile(file, contents, 'utf8');
  return true;
}
